### ISSUE TITLE
Boss Fights

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#111]
## Suggested Feature 
Add a boss fight (harder fight with enemy commander) to each level. After X days has passed have boss attack player. Boss fight exists on a  node and can be triggered at any point.

**Comment by snayff** [comment]
@PuddingChef should the level boss be known to the player up front, at the beginning of the level? If the boss has certain strengths and weaknesses then this allows some counterplay, instead of getting to the end to find the random boss. 

Or, taking a suggestion you made previously for something similar, we could have the boss be determined at the start and give the player clues as they explore, "The boss likes ranged.", "The boss only uses fire." etc.? The risk is that the clues aren't meaningful enough; the boss uses fire, so what? I can't do anything about it. In that case the player ignores it anyway and just goes for the end boss whenever.
