### ISSUE TITLE
Constrain Entity Positions

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#89]
## Suggested Feature 
Constrain entities in a unit to a circular region. This will make it easier to track units and manage their interactions, it will also serve as a central point and location for the unit. 

## Requirements 
1. Units have an area that defines where the entities can go. 
2. Entities cannot leave the area of the unit. 
3. Each Unit has its own area size. 
4. The area of the unit is displayed as a ring/circle.
    1. Have the ring around the player's units use a different colour to the enemy's units.
5. The central point of the unit is used a the units position for purposes of targeting. 
6. The central point  of the unit is displayed as a banner.

**Comment by snayff** [comment]
@DaFluffyPotato Added 4.1. Let me know if that changes anything or causes any concerns.

**Comment by DaFluffyPotato** [comment]
Upon further inspection, this will not work under the existing combat system due to pushing and terrain. Unless I add an absurd amount of rules or completely remove "entities" as a concept, this is not possible (without serious negative side effects).

I will implement this concept on some level with the way AI targets and moves, but I will use an alternative solution to achieve the goal of visually tracking the units.

To clarify:
1. Will only be applied for some steps of the AI instead of the whole thing (due to terrain/pushing).
2. Will not implement.
3. Will implement (to the extent it's used for 1.).
4. I will implement an alternative visual tracking system.
5. This is not necessary because of the way targeting works now.
6. This will track in a different way since the unit's visual shape is no longer always a circle.

**Comment by DaFluffyPotato** [comment]
here's what it looks like:
![image](https://user-images.githubusercontent.com/28032741/132974511-c3ae0319-9c54-4249-b166-065cea5f6d3c.png)

**Comment by DaFluffyPotato** [comment]
For fun, here's the masking spaghetti (literally using spaghetti made up of lines for masking) to create the borders:
![image](https://user-images.githubusercontent.com/28032741/132974615-f54bad1f-8c92-4a3b-9662-0060f82ecf41.png)

**Comment by DaFluffyPotato** [comment]
made it look nicer
![image](https://user-images.githubusercontent.com/28032741/132976143-ac44d84c-7d20-452c-a3b4-26b5f91463c9.png)

**Comment by snayff** [comment]
@DaFluffyPotato it looks decent, but I am not sure why the requirements can't be implemented as described. Couldnt the central point act as a tether to hold entities within the unit?

**Comment by DaFluffyPotato** [comment]
No, because units could get pushed around and get stuck on terrain. With pushing, it’s impossible to keep them in. If you try to pull them in forcibly, they’ll get caught on terrain and glitch out. If you make the others wait, the whole unit will get stuck if one entity gets body blocked. That’s just some of the issues. Instead, I’m making the units group up within a specified max range at certain phases, so they will be generally grouped up.

**Comment by snayff** [comment]
Closed in #146 .
Entities frequently get caught on terrain and this is then limiting the movement of the other entities in the unit. This will be worked on as a stand alone bug.

**Comment by DaFluffyPotato** [comment]
Are you sure you're not using the swarm AI when they get stuck? The new AI doesn't do that as far as I know.

**Comment by snayff** [comment]
@DaFluffyPotato Could well be. I'll update the units to the new AI types and test again.

**Comment by snayff** [comment]
@DaFluffyPotato changed all the AI to `light` or `heavy` and while it happens much less some units still get stuck.
